[0m12:53:23.832637 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5B6ED2DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5B668D670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5B668C770>]}


============================== 12:53:23.875643 | 9fd1054a-d0e1-4495-a351-60fa8e351098 ==============================
[0m12:53:23.875643 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:53:23.889926 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\andre\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init spacex_project', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:53:24.356831 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/andre/.dbt')}
[0m12:53:24.361892 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:53:24.391706 [debug] [MainThread]: Starter project path: C:\Users\andre\anaconda3\Lib\site-packages\dbt\include\starter_project
[0m12:53:24.450939 [info ] [MainThread]: 
Your new dbt project "spacex_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:53:24.450939 [info ] [MainThread]: Setting up your profile.
[0m12:55:36.165717 [info ] [MainThread]: Profile spacex_project written to C:\Users\andre\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:55:36.168705 [debug] [MainThread]: Command `dbt init` succeeded at 12:55:36.167707 after 133.12 seconds
[0m12:55:36.168705 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5B6ED2DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5B98FCE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5B5C1E5A0>]}
[0m12:55:36.169707 [debug] [MainThread]: Flushing usage events
[0m12:55:36.709704 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:49:48.324604 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025439BB98E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025436797080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025439BBBE60>]}


============================== 13:49:48.345239 | 2897de7b-0de1-43df-9c2f-ea18b8d73d63 ==============================
[0m13:49:48.345239 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:49:48.356737 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\andre\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m13:49:48.358825 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\andre\OneDrive\Desktop\SpaceX-Data-Pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:49:48.366834 [debug] [MainThread]: Command `dbt run` failed at 13:49:48.365844 after 1.06 seconds
[0m13:49:48.369824 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025439745F40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025436797080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025438AD0410>]}
[0m13:49:48.370812 [debug] [MainThread]: Flushing usage events
[0m13:49:48.887503 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:07:02.147534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224741A7C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022471DE2BA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022471F59460>]}


============================== 18:07:02.184216 | 105bad8d-e3a4-46bc-bb70-d252026abd8a ==============================
[0m18:07:02.184216 [info ] [MainThread]: Running with dbt=1.9.4
[0m18:07:02.188621 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\andre\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt docs serve', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:07:02.191377 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\andre\OneDrive\Desktop\SpaceX-Data-Pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:07:02.196450 [debug] [MainThread]: Command `dbt docs serve` failed at 18:07:02.196450 after 0.94 seconds
[0m18:07:02.198437 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002247491AAB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022474844AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022474541100>]}
[0m18:07:02.199435 [debug] [MainThread]: Flushing usage events
[0m18:07:02.814796 [debug] [MainThread]: An error was encountered while trying to flush usage events
